[package]
name = "container"
version = "0.1.0"
authors = ["Dylan Reid <dgreid@chromium.org>"]

[dependencies]
libc = "*"
nix = { git = "http://github.com/nix-rust/nix.git" }
tempdir = "*"
seccomp-sys = "*"
caps = { path = "../caps" }
