[package]
name = "container_config_reader"
version = "0.1.0"
authors = ["Dylan Reid <dgreid@chromium.org>"]

[dependencies]
container = { path = "../container" }
nix = { git = "http://github.com/nix-rust/nix.git" }
serde = "*"
serde_json = "*"
serde_derive = "*"

