[package]
name = "run_oci"
version = "0.1.0"
authors = ["Dylan Reid <dgreid@chromium.org>"]

[dependencies]
container = { path = "../container" }
container_config_reader = { path = "../container_config_reader" }
nix = "*"
serde = "*"
serde_json = "*"
